### ISSUE TITLE
Traceback error out of the blue

### ISSUE THREAD

**Issue by JellyfishMunky** [Voldrix/onlyfans-dl-2#126]
Checked the usual sess cookie and ipchicken issues but getting this error now, despite not changing anything and it was working just fine a few days earlier.

`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/CC3C88DE3C88C544/of.py", line 275, in <module>
    dynamic_rules = requests.get('https://raw.githubusercontent.com/Growik/onlyfans-dynamic-rules/main/rules.json').json()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 4 (char 3)
`

**Comment by janolehuebner** [comment]
The dynamic rules json is gone for now. See #124

**Comment by Voldrix** [comment]
Should be working now, try the latest patch.
