### ISSUE TITLE
KeyError: media

### ISSUE THREAD

**Issue by BrickTheNick** [Voldrix/onlyfans-dl-2#17]
I get the following error when executing the script. Nothing happens after the error. N odownload or anything.

Downloading content to stellaviolet
Found 215 posts
Traceback (most recent call last):
  File "C:\Users\Nick\Downloads\onlyfans-dl-2-master\onlyfans-dl.py", line 233, in <module>
    get_content("posts", "/users/" + PROFILE_ID + "/posts")
  File "C:\Users\Nick\Downloads\onlyfans-dl-2-master\onlyfans-dl.py", line 190, in get_content
    if len(post["media"]) > 1: # Don't put single photo posts in a subfolder
KeyError: 'media'

**Comment by Voldrix** [comment]
I added a check for that array element's existence. It should gracefully skip results without it now. Try the latest commit.
