### ISSUE TITLE
Receiving errors. No clue what the issue could be.

### ISSUE THREAD

**Issue by rubberban** [Voldrix/onlyfans-dl-2#39]
I keep receiving these errors randomly. There is no pattern to the errors, that I can see. Sometimes its immediately after the command, sometimes its after 4 profiles, sometimes it doesn't happen. Ran the file successfully yesterday; today I got the error multiple times. Closed power shell, reopened, received it once again, and then haven't received it since.

Would appreciate any feedback as to what the cause could be. Python is up to date, as well as the OF-dl file.

> Traceback (most recent call last):
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1349, in getresponse
    response.begin()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1349, in getresponse
    response.begin()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "\onlyfans-dl.py", line 236, in <module>
    get_content("posts", "/users/" + PROFILE_ID + "/posts")
  File "\onlyfans-dl.py", line 180, in get_content
    posts = api_request(API_LOCATION,MEDIATYPE)
  File "\onlyfans-dl.py", line 94, in api_request
    list_extend = requests.get(API_URL + endpoint, headers=API_HEADER, params=getParams).json()
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by Voldrix** [comment]
Connection problems with the requests library. Are you using the latest commit, because I did add some basic error handling a while back? When the error does occur is it always on the same profile? Intermittent problems are hard to track down, do you happen to be on a connection with potential packet loss like 4G or weak Wi-Fi?

**Comment by rubberban** [comment]
Thanks for getting back with me.

Yes, **I'm using the latest file** where you added a null check.

As I stated, it happens randomly. Since the API returns profiles in the same order every time when using "all", **it is never on the same profile**. Sometimes it happens immediately, other times its near the end. I am connected directly, **with an Ethernet cable**, to my router.

I assumed it was something on my end, but I wanted to ask here because I couldn't find any solutions online regarding these specific issues since it happens seemingly randomly.

**Comment by Ratione** [comment]
Experiencing similar problems: pastebin.com/UBLLsKB6

Except it hasn't worked for me at all. I cannot get the program to download anything from any profile. I double checked all my variables, and am using a version I downloaded the same day I post this.

**Comment by Ratione** [comment]
I should note that a few months ago, I was able to get the old version working on this exact setup. Nothing about my hardware or network settings has changed. Idk if thats relevant.

**Comment by Sgt-Nukem** [comment]
> Experiencing similar problems: pastebin.com/UBLLsKB6

Besides not able to download anything, these are not so similar at all:
* Yours is "Temporary failure in name resolution" - which means your DNS resolver gets asked to provide the IP address for the OF domain but didn't respond. Thus the receiving end is unknown, so the connection is not set up at all in the first place.
* The OP however got "Remote end closed connection without response" - which means there was a connection set up and a request sent (and thus the DNS resolve working), but then the connection was dropped suddenly without a response. Something you would get by janking out the ethernet cable or loosing WiFi connection or when a firewall suddenly decides this could be a malicious connection and shuts it down for good.

**Comment by Voldrix** [comment]
Since the old script will no longer work, this issue is no longer valid. Update to the latest commit, and if you experience the same issue, open a new ticket.
